# Generated by scripts/package.py only after signed, notarized artifacts exist.
cask "spacejam" do
  version "0.1.0"
  sha256 "4a14a1439cb290e61d09f24e1c5ba12aa2eec7fd25a9722bf8007518352ed80b"

  url "https://github.com/rkaregaran/SpaceJam/releases/download/v#{version}/SpaceJam-#{version}-arm64.dmg"
  name "SpaceJam"
  desc "Set the speed of desktop switching on macOS"
  homepage "https://github.com/rkaregaran/SpaceJam"

  depends_on arch: :arm64
  depends_on macos: :golden_gate
  depends_on maximum_macos: :golden_gate

  app "SpaceJam.app"

  uninstall quit: "dev.rzkr.SpaceJam"

  zap trash: [
    "~/Library/Preferences/dev.rzkr.SpaceJam.plist",
    "~/Library/Saved Application State/dev.rzkr.SpaceJam.savedState",
  ]

  caveats do
    <<~EOS
      Requires macOS 27. Open SpaceJam from Applications and enable
      its Accessibility permission. Physical trackpad swipes and fullscreen
      desktops keep their native behavior.
    EOS
  end
end
