# Generated by scripts/package.py only after signed, notarized artifacts exist.
cask "spacejam" do
  version "0.3.2"
  sha256 "99abaff294fba53bfc246f9bc6c89d5640037870b817a21557ad0027b27e5692"

  url "https://github.com/rkaregaran/SpaceJam/releases/download/v#{version}/SpaceJam-#{version}-arm64.dmg"
  name "SpaceJam"
  desc "Set the speed of desktop switching on macOS"
  homepage "https://github.com/rkaregaran/SpaceJam"

  depends_on arch: :arm64
  depends_on macos: :tahoe
  depends_on maximum_macos: :golden_gate

  app "SpaceJam.app"

  uninstall quit: "dev.rzkr.SpaceJam"

  zap trash: [
    "~/Library/Preferences/dev.rzkr.SpaceJam.plist",
    "~/Library/Saved Application State/dev.rzkr.SpaceJam.savedState",
  ]

  caveats do
    <<~EOS
      Requires macOS 26 or 27. Open SpaceJam from Applications and enable
      its Accessibility permission. Physical trackpad swipes and fullscreen
      desktops keep their native behavior.
    EOS
  end
end
